apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orchestrator-releng-tenant
# List of resources to include in the kustomization: they are expected to be other folders with kustomization.yaml,
# one per application. Objects shared across applications can stay in the _base/ folder.
resources:
  - operator
  - serverless-workflows
  - fbc-v4-14
