apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: playbook-dispatcher-enterprise-contract
  namespace: hcc-pipeline-tenant
spec:
  application: playbook-dispatcher
  contexts:
  - description: Application testing
    name: application
  params:
  - name: POLICY_CONFIGURATION
    value: rhtap-releng-tenant/app-interface-standard
  resolverRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract-redhat-no-hermetic.yaml
    resolver: git
