resources:
  - persistent-volume-claim.yaml
  - rb-ecp.yaml
  - rb-konflux-service-release.yaml
  - rb-konflux-integration-service.yaml
  - rb-release-pipelines.yaml
  - rb-releng-gitops-repo-ro.yaml
  - rb-releng-gitops-repo-rw.yaml
  - rb-redhat-acm-service-account.yaml
  - sa-redhat-acm-service-account.yaml
  - rb-redhat-acs-service-account.yaml
  - sa-redhat-acs-service-account.yaml
  - sa-konflux-service-release.yaml
  - sa-konflux-integration-service.yaml
  - sa-release-app-interface-prod.yaml
  - sa-release-app-interface-staging.yaml
  - sa-release-index-image-prod.yaml
  - sa-release-index-image-staging.yaml
  - sa-release-github-terraform-dev.yaml
  - sa-release-github-terraform-prod.yaml
  - sa-release-registry-dev.yaml
  - sa-release-registry-prod.yaml
  - sa-release-registry-staging.yaml
  - sa-releng-gitops-repo-ro.yaml
  - sa-releng-gitops-repo-rw.yaml
  - remote-secrets

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhtap-releng-tenant
