resources:
- release_plan_admission-application-service.yaml
- release_plan_admission-build.yaml
- release_plan_admission-external-secrets.yaml
- release_plan_admission-image-controller.yaml
- release_plan_admission-internal-services.yaml
- release_plan_admission-release-service.yaml
- release_plan_admission-segment-bridge.yaml
- release_plan_admission-tools.yaml
- release_plan_admission-remotesecret.yaml
- release_plan_admission-spi.yaml
- release_plan_admission-build-trusted-artifacts.yaml
- release-service-account-rb.yaml
- ec-policy.yaml
- persistent-volume-claim.yaml
- release-pipeline-sa.yaml
- release_plan_admission-integration-service.yaml
- remote-secrets
- release_plan_admission-o11y.yaml
- rb-ecp.yaml
- ec-policy-o11y.yaml
- ec-policy-release-service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rh-managed-rhtap-ser-tenant
