resources:
- release-service-account-rb.yaml
- ec-policy.yaml
- persistent-volume-claim.yaml
- release-pipeline-sa.yaml
- remote-secrets
- rb-ecp.yaml
- ec-policy-o11y.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rh-managed-rhtap-ser-tenant
